apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-app
        image: gcr.io/psychic-apex-434412-t1/django-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "django_crud_db"
        - name: DB_USER
          value: "user_alok"
        - name: DB_PASSWORD
          value: "user_password"